name: Workflow_Inputs

on:
  workflow_dispatch:
    
jobs:

  call-build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Build Successful"
 
  deploy-dev:
     runs-on: ubuntu-latest
     needs: [ call-build ]
     name: Deploy to DEV
     environment: development

     steps:
       - run: |
           echo "Deployment target is DEV"
       
  deploy-qa:
    runs-on: ubuntu-latest
    needs: [ call-build ]
    name: Deploy to DEV
    environment: sandbox

    steps:
      - run: |
          echo "Deployment target is DEV"

      
  deploy-prd:
    runs-on: ubuntu-latest
    needs: [ call-build ]
    name: Deploy to DEV
    environment: production

    steps:
      - run: |
          echo "Deployment target is DEV"