name: Workflow_Inputs

on:
  workflow_dispatch:
    
jobs:

  call-build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Build Successful"
 
  deploy-dev:
     runs-on: ubuntu-latest
     needs: [ call-build ]
     name: Deploy to Dev
     environment: development

     steps:
       - run: |
           echo "Deployment environment is Development"
       
  deploy-qa:
    runs-on: ubuntu-latest
    needs: [ deploy-dev ]
    name: Deploy to SandBox
    environment: sandbox

    steps:
      - run: |
          echo "Deployment environment is Sandbox"

      
  deploy-prd:
    runs-on: ubuntu-latest
    needs: [ deploy-qa ]
    name: Deploy to Prod
    environment: production

    steps:
      - run: |
          echo "Deployment environment is Production"